stages:
  - build
  - deploy

build:
  image: node:latest
  stage: build
  variables:
    VITE_API_URL: 'https://gostdoc.ru/api/'
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist

deploy:
  image: alpine
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - apk update
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_ed25519
    - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh $SSH_USER@$SSH_HOST "rm -fdr ~/gost-doc/dist && mkdir -p ~/gost-doc"
    - scp -r dist/ $SSH_USER@$SSH_HOST:~/gost-doc/
  only:
    - main
