image: "node:21-slim"

stages:
  - publish

publish:
  stage: publish
  variables:
    GIT_STRATEGY: clone
  before_script:
    - apt-get update && apt-get install git -y
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - git config --global user.email "${GIT_USER_EMAIL}"
    - git config --global user.name "${GIT_USER_NAME}"
    - yarn
    - yarn build
    - commitMessage=$(git log -1 --pretty=%B)
    - tagname=$(git tag --points-at HEAD)
    - version=${tagname:1}
    # Решение проблемы с циклическим вызовом
    - git config --global user.email "artemryskal01@gmail.com"
    - git config --global user.name "artemryskal"
    - git tag -d $tagname
    - git commit --amend -m "[ci skip] ${commitMessage}" --no-verify
    - git tag -a $tagname -m ''

    # Публикация в gitlab
    - git push https://${GIT_SYNC_USER}:${GIT_SYNC_TOKEN}@git.nlmk.com/$CI_PROJECT_PATH.git --follow-tags main:main

    # Публикация в npm
    - yarn publish --new-version $version --verbose

  only:
    - main
